name: billova_retail
description: "Billova Retail — Professional Billing Software"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # Database
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^0.4.5+3
  path: ^1.9.1
  path_provider: ^2.1.5

  # Supabase
  supabase_flutter: ^2.8.4

  # PDF & Printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # Charts
  fl_chart: ^0.70.2

  # Formatting
  intl: ^0.20.2

  # Typography
  google_fonts: ^6.2.1

  # Local Storage
  shared_preferences: ^2.5.3

  # Utilities
  uuid: ^4.5.1

  # URL Launcher (WhatsApp)
  url_launcher: ^6.3.2

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # HTTP
  http: ^1.2.2

  crypto: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/barakah_logo.jpg
    - assets/images/login/slide_1.jpg
    - assets/images/login/slide_2.jpg
    - assets/images/login/slide_3.jpg
    - assets/images/login/slide_4.jpg
