-- GST support: add gst_rate to items, gst_amount/cgst/sgst to sales, gst_number to customers
ALTER TABLE items ADD COLUMN IF NOT EXISTS gst_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS gst_amount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cgst DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS sgst DOUBLE PRECISION DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gst_number TEXT DEFAULT '';
